baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Gestalt Hugo Beta'

## Changes the default behaviour from a post permalink will be /blog/:filename:
[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

# `date-and-tags.html` partial pulls a date format from the `config file` – if the date format value is not specified, it defaults to `Jan 2, 2006`. So update config.toml again with the dateFormat param.
[params]
dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."
  defaultAuthor = "Dwayne Cyrus"

[taxonomies]
  category = "categories"
  tag = "tags"